dist: trusty
sudo: required
services:
  - docker
language: node_js
node_js:
  - "7"
before_install:
  - docker pull influxdb:1.2.4
  - export container_id=$(docker run -dit -p 8086:8086 influxdb:1.2.4)
  - sleep 30
  - docker logs ${container_id}
  - sudo apt-get install python3
  - python3 --version
  - ./scripts/test.py
after_script: NODE_ENV=test istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
