dist: trusty
sudo: required
services:
  - docker
language: node_js
node_js:
  - "7"
before_install:
  - docker pull influxdb:1.2.4
  - docker run -p 8086:8086 influxdb:1.2.4
  - export container_id=$(docker ps -a)
  - docker logs ${container_id}
  - sudo apt-get install python3
  - python3 --version
  - ./scripts/test.py
